classificação = ('Palmeiras', 'Grêmio', 'Atlético-Mg', 'Flamengo', 'Botafogo', 'Bragantino', 'Fluminense', 'Athletico-PR', 'Internacional', 'Fortaleza', 'São Paulo', 'Cuiabá', 'Corinthians', 'Cruzeiro', 'Vasco da Gama', 'Bahia', 'Santos', 'Goiás', 'Coritiba', 'America-MG')
clube = classificação.index('Athletico-PR')
print('-='*40)
print(f'Lista de times dos Brasileirão: {classificação}')
print('-='*40)
print(f'Os 5 primeiros são {classificação[:5]}')
print('-='*40)
print(f'Os 4 últimos são {classificação[16:20]}')
print('-='*40)
print('Times em ordem alfabética', sorted(classificação))
print('-='*40)
print(f'Athletico-PR está na {clube}ª colocação')
